---
title: "Doner based imputation methods"
subtitle: "with apllications in R"
author: "Aksel Thomsen (akt@dst.dk)"
institute: "Statistics Denmark"
date: "2020/12/7"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r, setup, include=FALSE}
```

# Outline

1. Theory

  1. Imputation in general
  1. Donor-based imputation methods
  
1. In practice

  1. Analyze
  1. Methods
  1. How to in `R`

---
class: inverse, center, middle

# Theory

---
class: inverse, center, middle

# In practice

---

# Simulated LFS

```{r, message=FALSE}
library(tidyverse)
lfs <- read_csv("example.csv", col_types = "inffnn")

head(lfs)
```

---

```{r}
summary(lfs)
```

--

## Partial non-response!

--- 
# a

```{r}
lfs %>% count(employed, is.na(hours))
```

--

## Routing: employed = 0 => hours not asked

--

## Logical imputation: hours answered => the person is employed

---

a
